version: '3.1'
volumes:
  pg_demo:
services:
  demo_db:
    image: postgres
    restart: always
    environment:
      - POSTGRESS_USER=admin
      - POSTGRESS_PASSWORD=admin
      - POSTGRESS_DB=demo_db
    volumes:
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"